### ISSUE TITLE
Responsive Sidebar and Navbar

### ISSUE THREAD

**Issue by minhas309** [Final-Year-Project-ShipEase/shipease-frontend#9]
The Navbar and Side bar is currently not very responsive. We want to make it responsive so that it can adjust It's self according to the screen size and resolution. 

Contribution rules are simple:
- Reply in this conversation or mail me at `minhas1412981@gmail.com`
- Create a separate branch with a proper naming convention. 
- Commit messages should be meaning full
- Create PR for staging branch.

**Comment by M-Muntazer-Mehdi** [comment]
1. Addressed the responsiveness issue in the Navbar and Side bar.
2. The layout now adapts to different screen sizes and resolutions,
3. Ensuring a seamless user experience across various devices.
